### PR TITLE
Adding support for Postgresql's ILIKE comparison operator

### PR DESCRIPTION
**Pull request by bcardarella**
Trying again?

### CODE REVIEW

**Comment by pedromg** [comment]
I found that in my Merb app, with dm-postgres-adapter, I had to patch:
dm-postgres-adapter-1.0.2/lib/dm-postgres-adapter/adapter.rb
dm-core-1.0.2/lib/dm-core/query/conditions/comparison.rb

Then, symbol.rb needs _not_ to be patched, but _must_ be reloaded:
dm-core-1.0.2/lib/dm-core/core_ext/symbol.rb
for the ilike method to be created, since the symbol :ilike is already in the: DataMapper::Query::Conditions::Comparison.slugs
or the error "undefined method `ilike' for :name:Symbol" pops out.

@dkubb do you confirm this ? 
@bcardarella could you please try this, instead of patching your symbol.rb ? Just require '...core-ext/symbol.rb' again without changing it please.

**Comment by dkubb** [comment]
@pedromg: That shouldn't be required. As long as dm-postgres-adapter/core-ext/symbol.rb is required, it should add Symbol#ilike.

Perhaps it's a require order issue. dm-core should be required before this patched version of dm-postgres-adapter, not afterwards.

**Comment by pedromg** [comment]
@dkubb: I made this script and if Symbol class isn't loaded after the patch, it won't seem to work:
http://github.com/pedromg/dm-postgres-adapter_patch_demo/blob/master//dm_pg_ilike_demo.rb

**Comment by r3n4ud** [comment]
@dkubb It will be really usefull to see ilike implemented and I'm surprised the patch has not been merged 2 years ago. It seems to me that ilike should be implemented in do. Am I wrong?

If MySQL's LIKE is not case-sensitive, we have behavior discrepancies between at least MySQL and Postgresql. Wouldn't it be better to have something more homogeneous there, i.e. use ILIKE behind the hood or implement ilike at do level?

**Comment by bcardarella** [comment]
Yeah I was pretty surprised when it wasnt pulled in as ilike is very Postgres specific

**Pull request closed without merging**
